spring:
  application:
    name: gateway-service
    
server:
  port: 8888
  
zuul:
  routes:
    project-service:
      path: /project/**
      service-id: project-service
      strip-prefix: false
    project-location-service:
      path: /location/**
      service-id: project-service
      strip-prefix: false
    user-service:
      path: /users/**
      service-id: user-service
      strip-prefix: false
    user-resource-service:
      path: /resources/**
      service-id: user-service
      strip-prefix: false
    user-grades-service:
      path: /grades/**
      service-id: user-service
      strip-prefix: false
    user-competency-service:
      path: /competency/**
      service-id: user-service
      strip-prefix: false
    skill-service:
      path: /skills/**
      service-id: skill-cert-service
      strip-prefix: false
    skill-group-service:
      path: /skill-group/**
      service-id: skill-cert-service
      strip-prefix: false
    certifications-service:
      path: /certifications/**
      service-id: skill-cert-service
      strip-prefix: false

eureka:
  client:
    register-with-eureka: true
    service-url:
#     http://localhost:8761/eureka
      defaultZone: http://ec2-52-33-125-157.us-west-2.compute.amazonaws.com:8761/eureka
      useDnsForFetchingServiceUrls: true
      eurekaServerDNSName: http://ec2-35-153-210-251.compute-1.amazonaws.com
      
jwt:
  security:
    key: j3H5Ld5nYmGWyULy6xwpOgfSH++NgKXnJMq20vpfd+8=t