spring:
  application:
    name: gateway-service
    
server:
  port: 8888
  
zuul:
  routes:
    project-service:
      path: /project/**
      service-id: project-service
      strip-prefix: false
    user-service:
      path: /users/**
      service-id: user-service
      strip-prefix: false
    skill-cert-service:
      path: /skills/**
      service-id: skill-cert-service
      strip-prefix: false

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      lease-expiration-duration-in-seconds: 2
      lease-renewal-interval-in-seconds: 1
      
jwt:
  security:
    key: j3H5Ld5nYmGWyULy6xwpOgfSH++NgKXnJMq20vpfd+8=t